In [ ]:
numero_int = -3 # int
#Em python não é nescessário definir o tipo

numero_float = 3.5

In [2]:
caracter = 'a'
palavra = 'Python'
palavra_dois = 'Aprendendo'
#concatenando strings
print(palavra_dois + ' ' + palavra)

Aprendendo Python


In [3]:
#input para o usuário entrar com os dados 
idade = int(input())
print('Sua idade é',idade, 'anos.')

 15


Sua idade é 15 anos.


In [8]:
#Manipulação de string
a = 'casaco'
print(a)

maiuscula = a.upper()
print(maiuscula)

metade_palavra = a[0:3]
print(metade_palavra)

b = a.replace('aco', 'inha')
print(b)


casaco
CASACO
cas
casinha


In [9]:
#Matrizes
import numpy as np

matriz = np.array([[2,3,1],[4,5,7]])

matriz


array([[2, 3, 1],
       [4, 5, 7]])

In [10]:
matriz.shape

(2, 3)

In [11]:
matriz[0]

array([2, 3, 1])

In [12]:
matriz[1]

array([4, 5, 7])

In [13]:
matriz[0][0]

np.int64(2)

In [19]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7


In [ ]:
#Função sem parâmetros e sem retorno
#Essa função apenas executa algo, mas não recebe valores nem retorna nada.
def saudacao():
    print("Olá, tudo bem?")

# Usando a função
saudacao()


In [ ]:
#Função com parâmetros e sem retorno
#Recebe valores de entrada (parâmetros), mas não devolve nada, apenas faz alguma ação (como imprimir).
def mostrar_dobro(numero):
    print(f"O dobro de {numero} é {numero * 2}")

# Usando a função
mostrar_dobro(5)



In [ ]:
#Função com parâmetros e com retorno
#Essa é a mais completa: recebe valores e retorna um resultado.
def soma(a, b):
    return a + b

# Usando a função
resultado = soma(3, 4)
print(f"A soma é: {resultado}")


# 📐 Módulo `math` em Python

O módulo `math` fornece acesso a funções matemáticas definidas pelo padrão C. Ele é útil para cálculos matemáticos mais avançados que vão além das operações básicas.

Documentação oficial: [https://docs.python.org/pt-br/3/library/math.html](https://docs.python.org/pt-br/3/library/math.html)

---

## ✅ Importação do Módulo

```python
import math


In [9]:
#Biblioteca Math
https://docs.python.org/pt-br/3/library/math.html
import math

math.sqrt(9)

3.0

In [3]:
math.sin(45)

0.8509035245341184

In [4]:
math.cos(45)

0.5253219888177297

In [5]:
math.log(1000, 10)

2.9999999999999996

In [6]:
math.log(32, 2)

5.0

In [7]:
#numero euler 
math.e

2.718281828459045

# 📅 Módulo `datetime` em Python

O módulo `datetime` fornece classes para manipulação de datas e horas de forma simples e complexa.

📄 Documentação Oficial:  
[https://docs.python.org/pt-br/3.13/library/datetime.html](https://docs.python.org/pt-br/3.13/library/datetime.html)

---

## ✅ Importação

```python
import datetime


In [11]:
import datetime
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 'UTC',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [12]:
datetime.date.today()

datetime.date(2025, 7, 3)

In [13]:
datetime.datetime.now()

datetime.datetime(2025, 7, 3, 11, 25, 26, 317400)

In [15]:
data = datetime.date(2020, 7, 10)

In [16]:
data

datetime.date(2020, 7, 10)

In [17]:
data.day

10

# 🎲 Módulo `random` em Python

O módulo `random` implementa geradores de números pseudoaleatórios para várias distribuições.

📄 Documentação Oficial:  
[https://docs.python.org/3/library/random.html](https://docs.python.org/3/library/random.html)

---

## ✅ Importação

```python
import random


In [18]:
import random 
random.random()

0.8772881804730036

In [20]:
random.randint(1,10)

8

In [22]:
random.randrange(0, 10, 2) 

2

In [23]:
x = ['X', 'D', 13, 17, 'x']
random.choice(x)

13

import time

# Pegar o horário atual
agora = time.localtime()
print("Ano:", agora.tm_year)
print("Hora:", agora.tm_hour)

# Formatar para string
data_formatada = time.strftime('%d/%m/%Y %H:%M:%S', agora)
print("Data e hora formatada:", data_formatada)

# Pausar execução
print("Esperando 3 segundos...")
time.sleep(3)
print("Continuando!")


In [24]:
import time as tm
tm.time()

1751554839.1960266

In [26]:
antes=tm.time()
lista = []
for i in range(0, 100000):
    lista.append(i)

depois= tm.time()

intervalo = depois - antes
print(f'Tempo: {intervalo} segundos')

Tempo: 0.009853839874267578 segundos


# Como carregar arquivos `.py` no Jupyter Notebook

- 🚀 **Quer algo rápido e direto como no Google Colab?**  
  Use o comando mágico `%run` para executar o arquivo `.py` diretamente no notebook:  
  ```python
  %run caminho/do/arquivo.py
Isso carrega todas as funções e variáveis do arquivo na sua sessão atual.

📦 Quer organização e reaproveitamento?
Prefira usar import para carregar seus módulos:

python
Copiar
Editar
import nome_do_arquivo
# ou
from nome_do_arquivo import funcao_especifica

Assim, seu código fica modular, fácil de manter e reutilizar em vários notebooks e projetos.

In [31]:
import saudacao as sd 
sd.saudacao('Guilherme')

'Olá, Guilherme! Seja bem-vindo ao Jupyter.'

In [32]:
print('saudacao está na pasta Python' )

saudacao está na pasta Python


# 🚨 Tratamento de Erros e Exceções em Python

Em Python, erros e exceções são eventos que ocorrem durante a execução de um programa, que interrompem seu fluxo normal. O tratamento adequado desses erros é fundamental para garantir que o programa continue funcionando ou informe o problema de forma clara.

---

## ⚠️ Diferença entre Erro e Exceção

- **Erro**: Problema no código que geralmente impede o programa de rodar (ex.: erro de sintaxe).
- **Exceção**: Evento que ocorre durante a execução (runtime), podendo ser tratado para evitar que o programa pare.

---

## 🛠️ Blocos para Tratamento de Exceções
- NameError: variável nao foi definida
- TypeError: tipos de dados incompatíveis
- RuntimeError: erro de execução
- SyntaxError: sintaxe digitada é inválida e não reconhecida pelo interpretador
- ZeroDivisorError: divisão por zero
- IndexError: índice está fora da coleção

### `try` e `except`

```python
try:
    # Código que pode gerar uma exceção
    resultado = 10 / 0
except ZeroDivisionError:
    # Código para tratar a exceção específica
    print("Não é possível dividir por zero!")


In [33]:
3 = 4

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (732916017.py, line 1)

In [34]:
print (3 / 0)

ZeroDivisionError: division by zero

In [35]:
print(nome)

NameError: name 'nome' is not defined

In [36]:
2.3 / cachorro

NameError: name 'cachorro' is not defined

In [37]:
c = [1,2,3,4,5]
c[5]

IndexError: list index out of range

In [39]:
try:
    n = int(input('Digite um número inteiro'))
except:
    print('Valor inválido')
else:
    print(f'valor digitado é {n}')


Digite um número inteiro f


Valor inválido


In [41]:
while True:
    try:
        n = int(input('Digite um número inteiro'))
    except:
        print('Valor inválido')
    else:
        print(f'valor digitado é {n}')
        break


Digite um número inteiro f


Valor inválido


Digite um número inteiro f


Valor inválido


Digite um número inteiro f


Valor inválido


Digite um número inteiro f


Valor inválido


Digite um número inteiro f


Valor inválido


Digite um número inteiro 4


valor digitado é 4


# 📄 Manipulação de Arquivos em Python

A manipulação de arquivos em Python permite criar, ler, escrever e modificar arquivos de texto ou binários de forma simples e eficiente.

---

## 📌 Abrindo Arquivos com `open()`

```python
arquivo = open('exemplo.txt', 'modo')


Modo	Descrição
'r'	Leitura (padrão)
'w'	Escrita (sobrescreve o arquivo)
'a'	Acrescenta (append)
'x'	Cria novo arquivo, erro se já existir
'b'	Modo binário
't'	Modo texto (padrão)

📖 Lendo Arquivos
Ler todo o conteúdo:
python
Copiar
Editar
with open('exemplo.txt', 'r') as f:
    conteudo = f.read()
    print(conteudo)

# 🔍 Expressões Regulares (Regex) em Python

Expressões Regulares (Regex) são padrões usados para buscar, validar ou manipular textos. Em Python, o módulo responsável é o `re`.

---

## ✅ Importação

```python
import re

## 🛠️ Funções Básicas do Módulo `re`

| Função | Descrição | Exemplo |
|--------|-----------|---------|
| `re.match(padrao, texto)` | Verifica se o texto **começa** com o padrão | `re.match(r'\d+', '123abc')` |
| `re.search(padrao, texto)` | Procura o padrão em **qualquer parte** do texto | `re.search(r'\d+', 'abc123')` |
| `re.findall(padrao, texto)` | Retorna **todas** as ocorrências encontradas | `re.findall(r'\d+', 'abc123def456')` |
| `re.sub(padrao, substituto, texto)` | Substitui as ocorrências do padrão | `re.sub(r'\d+', '#', 'abc123')` |



## 📝 Principais Metacaracteres

| Símbolo | Significado | Exemplo |
|---------|------------|---------|
| `.`     | Qualquer caractere (exceto `\n`) | `a.b` → casa com `acb`, `arb` |
| `^`     | Início da string | `^Olá` → casa com strings que começam com "Olá" |
| `$`     | Fim da string | `fim$` → casa com strings que terminam com "fim" |
| `*`     | Zero ou mais repetições | `ab*` → casa com `a`, `ab`, `abb`, `abbb` |
| `+`     | Uma ou mais repetições | `ab+` → casa com `ab`, `abb`, `abbb` |
| `?`     | Zero ou uma repetição | `ab?` → casa com `a` ou `ab` |
| `{n}`   | Exatamente n repetições | `\d{4}` → casa com 4 dígitos (ex.: ano) |
| `{n,}`  | Pelo menos n repetições | `\d{2,}` → casa com dois ou mais dígitos |
| `{n,m}` | Entre n e m repetições | `\d{2,4}` → casa com de 2 a 4 dígitos |
| `[]`    | Conjunto de caracteres | `[aeiou]` → casa com qualquer vogal |
| `|`     | Ou (alternativa) | `gato|cachorro` → casa com "gato" ou "cachorro" |
| `()`    | Agrupamento | `(abc)+` → casa com `abc`, `abcabc`, etc. |



## 🅰️ Principais Sequências Especiais

| Código | Significado | Exemplo |
|--------|------------|---------|
| `\d`   | Qualquer dígito (0-9) | Casa com números como `0`, `5`, `9` |
| `\D`   | Qualquer caractere que **não** seja dígito | Casa com letras, símbolos, espaços |
| `\w`   | Caractere alfanumérico (`a-z`, `A-Z`, `0-9`, `_`) | Casa com `a`, `Z`, `3`, `_` |
| `\W`   | Qualquer caractere que **não** seja alfanumérico | Casa com `@`, `#`, espaço |
| `\s`   | Qualquer espaço em branco (espaço, tab, nova linha) | Casa com `' '` ou `\t` ou `\n` |
| `\S`   | Qualquer caractere que **não** seja espaço | Casa com qualquer caractere visível |


# 🧩 Orientação a Objetos (POO) em Python

A Programação Orientada a Objetos (POO) é um paradigma que organiza o código em torno de **objetos**, que são instâncias de **classes**.

---

## 🔑 Conceitos Básicos

| Conceito | Descrição |
|----------|-----------|
| **Classe** | Molde ou estrutura que define as características e comportamentos de um objeto. |
| **Objeto** | Instância de uma classe (algo concreto criado a partir de uma classe). |
| **Atributos** | Variáveis associadas a uma classe ou objeto. |
| **Métodos** | Funções definidas dentro de uma classe. |
| **Construtor (`__init__`)** | Método especial chamado automaticamente ao criar um objeto. |

---

## 📝 Criando uma Classe e Objeto

```python
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

    def apresentar(self):
        print(f"Olá, meu nome é {self.nome} e tenho {self.idade} anos.")

# Criando um objeto
p1 = Pessoa("Maria", 30)
p1.apresentar()


## 🔐 Encapsulamento

Controla o acesso aos atributos e métodos de uma classe.

```python
class ContaBancaria:
    def __init__(self, titular, saldo):
        self.titular = titular
        self.__saldo = saldo  # atributo privado

    def ver_saldo(self):
        print(f"Saldo de {self.titular}: R$ {self.__saldo:.2f}")

conta = ContaBancaria("João", 1000)
conta.ver_saldo()
Atenção: Atributos com __nome são considerados privados (não devem ser acessados diretamente fora da classe).

## 🔄 Herança

Permite criar novas classes baseadas em classes existentes.

```python
class Animal:
    def __init__(self, nome):
        self.nome = nome

    def falar(self):
        print("Som indefinido")

class Cachorro(Animal):
    def falar(self):
        print("Au Au!")

dog = Cachorro("Rex")
dog.falar()

## 🔗 Polimorfismo

Objetos de diferentes classes podem ter métodos com o **mesmo nome**, mas comportamentos diferentes.

```python
animais = [Cachorro("Rex"), Animal("Bicho")]

for animal in animais:
    animal.falar()  # cada um executa seu próprio método

## 🏷️ Métodos e Atributos Especiais

| Nome       | Descrição                               |
|------------|---------------------------------------|
| `__init__` | Construtor da classe                   |
| `__str__`  | Representação em string do objeto     |
| `__len__`  | Retorna o tamanho (quando aplicável)  |
| `__add__`  | Define comportamento para o operador `+` |

```python
class Produto:
    def __init__(self, nome, preco):
        self.nome = nome
        self.preco = preco

    def __str__(self):
        return f"{self.nome} - R$ {self.preco:.2f}"

p = Produto("Livro", 29.90)
print(p)  # Chama automaticamente __str__


## 🏆 Resumo das Vantagens da POO

- ✅ Organização do código  
- ✅ Reutilização (herança)  
- ✅ Facilita manutenção  
- ✅ Código mais próximo do mundo real  

